
TOP = ..
SOURCE = \
	bound_tracker.cpp\
	countdown_timer.cpp\
	countup_timer.cpp\
	debounce.cpp\
	driver_station_interface.cpp\
	fixVictor.cpp\
	input.cpp\
	interface.cpp\
	meta.cpp\
	motion_profile.cpp\
	negedge_trigger.cpp\
	network.cpp\
	output.cpp\
	perf_tracker.cpp\
	point.cpp\
	posedge_toggle.cpp\
	posedge_trigger.cpp\
	posedge_trigger_debounce.cpp\
	settable_toggle.cpp\
	speed_tracker.cpp\
	stall_monitor.cpp\
	string_utils.cpp\
	type.cpp\
	util.cpp\
	visitable.cpp

LIBNAME = util


include ../mkfiles/lib.mk
