
TOP = ..
SOURCE = \
	bound_tracker.cpp\
	countdown_timer.cpp\
	countup_timer.cpp\
	debounce.cpp\
	driver_station_interface.cpp\
	fixVictor.cpp\
	input.cpp\
	interface.cpp\
	meta.cpp\
	motion_profile.cpp\
	negedge_trigger.cpp\
	network.cpp\
	output.cpp\
	perf_tracker.cpp\
	point.cpp\
	posedge_toggle.cpp\
	posedge_trigger.cpp\
	posedge_trigger_debounce.cpp\
	settable_toggle.cpp\
	speed_tracker.cpp\
	stall_monitor.cpp\
	string_utils.cpp\
	type.cpp\
	util.cpp\
	visitable.cpp

TESTLIST = \
	bound_tracker_test\
	countdown_timer_test\
	countup_timer_test\
	debounce_test\
	driver_station_interface_test\
	fixVictor_test\
	input_test\
	interface_test\
	meta_test\
	motion_profile_test\
	negedge_trigger_test\
	network_test\
	output_test\
	perf_tracker_test\
	point_test\
	posedge_trigger_debounce_test\
	posedge_trigger_test\
	settable_toggle_test\
	string_utils_test\
	type_test\
	util_test

LIBNAME = util


include ../mkfiles/lib.mk

