
TOP = ..
SOURCE = \
	climber.cpp\
	drivebase.cpp\
	force.cpp\
	force_interface.cpp\
	gear_collector.cpp\
	gear_grabber.cpp\
	gear_lifter.cpp\
	gear_shifter.cpp\
	lights.cpp\
	log.cpp\
	main.cpp\
	monitor.cpp\
	motor_check.cpp\
	nop.cpp\
	pump.cpp\
	roller.cpp\
	roller_arm.cpp\
	shooter.cpp\
	sim.cpp\
	toplevel.cpp

LIBNAME = control


include ../mkfiles/lib.mk
