
TOP = ..
SOURCE = \
	climber.cpp\
	drivebase.cpp\
	force.cpp\
	force_interface.cpp\
	gear_collector.cpp\
	gear_grabber.cpp\
	gear_lifter.cpp\
	gear_shifter.cpp\
	lights.cpp\
	log.cpp\
	main.cpp\
	monitor.cpp\
	motor_check.cpp\
	nop.cpp\
	pump.cpp\
	roller.cpp\
	roller_arm.cpp\
	shooter.cpp\
	sim.cpp\
	toplevel.cpp

TESTLIST = \
	drivebase_test\
	force_interface_test\
	log_test\
	main_test\
	monitor_test\
	motor_check_test\
	nop_test\
	pump_test\
	sim_test\
	toplevel_test

LIBNAME = control


include ../mkfiles/lib.mk
