
TOP = ..
SOURCE = \
	align.cpp\
	autonomous.cpp\
	chain.cpp\
	executive.cpp\
	step.cpp\
	teleop.cpp\
	test.cpp\
	timed.cpp

TESTLIST = \
	exectest\
	steptest\
	teleoptest\
	timetest

LIBNAME = executive


include ../mkfiles/lib.mk


